import type { ElementType } from 'react'

import type { SvgIconProps } from '@mui/material/SvgIcon'
import {
  AccountBalance,
  AccountBalanceWallet,
  AdminPanelSettings,
  Analytics,
  Announcement,
  Api,
  Architecture,
  Archive,
  Assessment,
  Assignment,
  AttachMoney,
  AutoAwesome,
  AutoFixHigh,
  AutoGraph,
  Backup,
  BarChart,
  BatteryChargingFull,
  BatteryFull,
  Biotech,
  BugReport,
  Build,
  Business,
  BusinessCenter,
  Cable,
  CalendarToday,
  Call,
  CameraAlt,
  Campaign,
  Cast,
  CastConnected,
  Chat,
  Checklist,
  Cloud,
  CloudCircle,
  CloudDone,
  CloudDownload,
  CloudOff,
  CloudQueue,
  CloudSync,
  CloudUpload,
  Code,
  CompareArrows,
  Computer,
  ConnectWithoutContact,
  Construction,
  ContactMail,
  CorporateFare,
  CreditCard,
  Css,
  Dashboard,
  DataArray,
  DataExploration,
  DataObject,
  Dataset,
  DataThresholding,
  DataUsage,
  DesktopMac,
  DesktopWindows,
  DeveloperBoard,
  DeveloperMode,
  DeviceHub,
  Devices,
  Dns,
  DriveFolderUpload,
  ElectricBolt,
  Email,
  EmojiObjects,
  Engineering,
  FactCheck,
  FilterList,
  Fingerprint,
  FolderOpen,
  Forum,
  Functions,
  GppGood,
  Groups,
  Handyman,
  Headphones,
  HeadsetMic,
  Html,
  Hub,
  Insights,
  InsertChart,
  IntegrationInstructions,
  Inventory,
  Javascript,
  Key,
  Keyboard,
  Lan,
  Language,
  Laptop,
  Lightbulb,
  Link,
  LocalShipping,
  Lock,
  MarkEmailRead,
  LockPerson,
  Memory,
  Message,
  ModelTraining,
  MonetizationOn,
  Monitor,
  MonitorHeart,
  Mouse,
  NetworkCheck,
  NoEncryption,
  Notifications,
  NotificationsActive,
  OfflineBolt,
  Paid,
  Payment,
  Phone,
  PhoneAndroid,
  PhoneIphone,
  PieChart,
  PivotTableChart,
  Policy,
  PrecisionManufacturing,
  PriceCheck,
  Print,
  PrivacyTip,
  Psychology,
  Public,
  QueryStats,
  Receipt,
  RecordVoiceOver,
  RocketLaunch,
  Router,
  RssFeed,
  Scanner,
  Schedule,
  Schema,
  Science,
  Search,
  Security,
  SecurityUpdateGood,
  Send,
  Settings,
  Share,
  ShareLocation,
  Shield,
  ShoppingCart,
  ShowChart,
  SignalCellularAlt,
  SignalWifi4Bar,
  SimCard,
  Smartphone,
  SmartToy,
  Sms,
  Sort,
  Speaker,
  Speed,
  Storage,
  Store,
  SupportAgent,
  SwapHoriz,
  Sync,
  Tablet,
  TableChart,
  Task,
  Terminal,
  Timeline,
  TipsAndUpdates,
  TrendingUp,
  Tune,
  Tv,
  Usb,
  VerifiedUser,
  Videocam,
  ViewColumn,
  VpnKey,
  Watch,
  Web,
  WebAsset,
  Wifi,
  WifiOff,
  Work,
  WorkOutline
} from '@mui/icons-material'

export type IconComponent = ElementType<SvgIconProps>

export type ServiceIconCategory =
  | 'cloud'
  | 'security'
  | 'development'
  | 'data'
  | 'network'
  | 'devices'
  | 'business'
  | 'communication'
  | 'ai'

export const SERVICE_ICON_CATEGORIES: readonly ServiceIconCategory[] = [
  'cloud',
  'security',
  'development',
  'data',
  'network',
  'devices',
  'business',
  'communication',
  'ai'
] as const

type IconEntry = {
  name: string
  Icon: IconComponent
  keywords: string[]
  category: ServiceIconCategory
}

/** Curated IT / tech service icons for product and service tables. */
export const IT_SERVICE_ICONS: IconEntry[] = [
  // Cloud
  { name: 'Cloud', Icon: Cloud, category: 'cloud', keywords: ['cloud', 'hosting', 'saas', 'infrastructure'] },
  { name: 'CloudQueue', Icon: CloudQueue, category: 'cloud', keywords: ['cloud', 'queue', 'async', 'processing'] },
  { name: 'CloudDone', Icon: CloudDone, category: 'cloud', keywords: ['cloud', 'complete', 'sync', 'success'] },
  { name: 'CloudUpload', Icon: CloudUpload, category: 'cloud', keywords: ['upload', 'cloud', 'backup', 'migrate'] },
  { name: 'CloudDownload', Icon: CloudDownload, category: 'cloud', keywords: ['download', 'cloud', 'restore', 'sync'] },
  { name: 'CloudSync', Icon: CloudSync, category: 'cloud', keywords: ['cloud', 'sync', 'replication', 'refresh'] },
  { name: 'CloudOff', Icon: CloudOff, category: 'cloud', keywords: ['cloud', 'offline', 'disconnect', 'unavailable'] },
  { name: 'CloudCircle', Icon: CloudCircle, category: 'cloud', keywords: ['cloud', 'circle', 'platform', 'service'] },
  { name: 'Backup', Icon: Backup, category: 'cloud', keywords: ['backup', 'recovery', 'disaster', 'archive'] },
  { name: 'Sync', Icon: Sync, category: 'cloud', keywords: ['sync', 'replication', 'refresh', 'update'] },
  { name: 'Archive', Icon: Archive, category: 'cloud', keywords: ['archive', 'storage', 'retention', 'cold'] },
  { name: 'FolderOpen', Icon: FolderOpen, category: 'cloud', keywords: ['folder', 'files', 'storage', 'documents'] },
  { name: 'DriveFolderUpload', Icon: DriveFolderUpload, category: 'cloud', keywords: ['upload', 'drive', 'folder', 'migrate'] },
  { name: 'Public', Icon: Public, category: 'cloud', keywords: ['public', 'global', 'world', 'cdn'] },

  // Security
  { name: 'Security', Icon: Security, category: 'security', keywords: ['security', 'protect', 'cyber', 'safe'] },
  { name: 'Shield', Icon: Shield, category: 'security', keywords: ['shield', 'protection', 'firewall', 'secure'] },
  { name: 'Lock', Icon: Lock, category: 'security', keywords: ['lock', 'encryption', 'access', 'auth'] },
  { name: 'VpnKey', Icon: VpnKey, category: 'security', keywords: ['key', 'vpn', 'credentials', 'auth'] },
  { name: 'VerifiedUser', Icon: VerifiedUser, category: 'security', keywords: ['verified', 'trust', 'identity', 'compliance'] },
  { name: 'AdminPanelSettings', Icon: AdminPanelSettings, category: 'security', keywords: ['admin', 'security', 'settings', 'governance'] },
  { name: 'Key', Icon: Key, category: 'security', keywords: ['key', 'secret', 'credentials', 'token'] },
  { name: 'Policy', Icon: Policy, category: 'security', keywords: ['policy', 'compliance', 'governance', 'rules'] },
  { name: 'Fingerprint', Icon: Fingerprint, category: 'security', keywords: ['biometric', 'identity', 'auth', 'mfa'] },
  { name: 'PrivacyTip', Icon: PrivacyTip, category: 'security', keywords: ['privacy', 'gdpr', 'data', 'protection'] },
  { name: 'LockPerson', Icon: LockPerson, category: 'security', keywords: ['lock', 'user', 'access', 'identity'] },
  { name: 'GppGood', Icon: GppGood, category: 'security', keywords: ['privacy', 'shield', 'verified', 'secure'] },
  { name: 'SecurityUpdateGood', Icon: SecurityUpdateGood, category: 'security', keywords: ['patch', 'update', 'security', 'fix'] },
  { name: 'NoEncryption', Icon: NoEncryption, category: 'security', keywords: ['unencrypted', 'warning', 'security', 'risk'] },

  // Development
  { name: 'Code', Icon: Code, category: 'development', keywords: ['code', 'development', 'software', 'programming'] },
  { name: 'Terminal', Icon: Terminal, category: 'development', keywords: ['terminal', 'cli', 'shell', 'devops'] },
  { name: 'IntegrationInstructions', Icon: IntegrationInstructions, category: 'development', keywords: ['integration', 'api', 'connect', 'workflow'] },
  { name: 'DeveloperMode', Icon: DeveloperMode, category: 'development', keywords: ['developer', 'build', 'engineering', 'dev'] },
  { name: 'DeveloperBoard', Icon: DeveloperBoard, category: 'development', keywords: ['hardware', 'embedded', 'iot', 'board'] },
  { name: 'Api', Icon: Api, category: 'development', keywords: ['api', 'rest', 'graphql', 'integration'] },
  { name: 'Build', Icon: Build, category: 'development', keywords: ['build', 'tools', 'maintenance', 'repair'] },
  { name: 'BugReport', Icon: BugReport, category: 'development', keywords: ['bug', 'qa', 'testing', 'debug'] },
  { name: 'Settings', Icon: Settings, category: 'development', keywords: ['settings', 'configure', 'admin', 'setup'] },
  { name: 'Tune', Icon: Tune, category: 'development', keywords: ['tune', 'optimize', 'adjust', 'config'] },
  { name: 'Functions', Icon: Functions, category: 'development', keywords: ['functions', 'lambda', 'serverless', 'logic'] },
  { name: 'Web', Icon: Web, category: 'development', keywords: ['web', 'internet', 'browser', 'site'] },
  { name: 'WebAsset', Icon: WebAsset, category: 'development', keywords: ['web', 'asset', 'page', 'frontend'] },
  { name: 'Construction', Icon: Construction, category: 'development', keywords: ['construction', 'build', 'wip', 'project'] },
  { name: 'Handyman', Icon: Handyman, category: 'development', keywords: ['tools', 'fix', 'maintenance', 'repair'] },
  { name: 'Engineering', Icon: Engineering, category: 'development', keywords: ['engineering', 'technical', 'build', 'dev'] },
  { name: 'PrecisionManufacturing', Icon: PrecisionManufacturing, category: 'development', keywords: ['manufacturing', 'precision', 'engineering', 'automation'] },
  { name: 'Architecture', Icon: Architecture, category: 'development', keywords: ['architecture', 'design', 'blueprint', 'system'] },
  { name: 'Schema', Icon: Schema, category: 'development', keywords: ['schema', 'structure', 'model', 'database'] },
  { name: 'Javascript', Icon: Javascript, category: 'development', keywords: ['javascript', 'js', 'frontend', 'node'] },
  { name: 'Html', Icon: Html, category: 'development', keywords: ['html', 'markup', 'web', 'frontend'] },
  { name: 'Css', Icon: Css, category: 'development', keywords: ['css', 'styles', 'frontend', 'design'] },

  // Data
  { name: 'Storage', Icon: Storage, category: 'data', keywords: ['storage', 'database', 'disk', 'data'] },
  { name: 'Dataset', Icon: Dataset, category: 'data', keywords: ['dataset', 'data', 'records', 'warehouse'] },
  { name: 'DataObject', Icon: DataObject, category: 'data', keywords: ['json', 'data', 'object', 'api'] },
  { name: 'TableChart', Icon: TableChart, category: 'data', keywords: ['table', 'report', 'spreadsheet', 'data'] },
  { name: 'Analytics', Icon: Analytics, category: 'data', keywords: ['analytics', 'metrics', 'stats', 'reporting'] },
  { name: 'Insights', Icon: Insights, category: 'data', keywords: ['insights', 'intelligence', 'analysis', 'bi'] },
  { name: 'TrendingUp', Icon: TrendingUp, category: 'data', keywords: ['growth', 'trend', 'performance', 'kpi'] },
  { name: 'Assessment', Icon: Assessment, category: 'data', keywords: ['assessment', 'audit', 'report', 'review'] },
  { name: 'BarChart', Icon: BarChart, category: 'data', keywords: ['chart', 'bar', 'metrics', 'visualization'] },
  { name: 'PieChart', Icon: PieChart, category: 'data', keywords: ['chart', 'pie', 'distribution', 'metrics'] },
  { name: 'ShowChart', Icon: ShowChart, category: 'data', keywords: ['chart', 'line', 'trend', 'metrics'] },
  { name: 'InsertChart', Icon: InsertChart, category: 'data', keywords: ['chart', 'report', 'dashboard', 'visualization'] },
  { name: 'QueryStats', Icon: QueryStats, category: 'data', keywords: ['query', 'stats', 'sql', 'analytics'] },
  { name: 'DataUsage', Icon: DataUsage, category: 'data', keywords: ['usage', 'bandwidth', 'metrics', 'monitoring'] },
  { name: 'DataExploration', Icon: DataExploration, category: 'data', keywords: ['explore', 'discover', 'data', 'analysis'] },
  { name: 'DataArray', Icon: DataArray, category: 'data', keywords: ['array', 'data', 'structure', 'records'] },
  { name: 'DataThresholding', Icon: DataThresholding, category: 'data', keywords: ['threshold', 'alert', 'monitoring', 'data'] },
  { name: 'FilterList', Icon: FilterList, category: 'data', keywords: ['filter', 'sort', 'query', 'search'] },
  { name: 'Sort', Icon: Sort, category: 'data', keywords: ['sort', 'order', 'rank', 'list'] },
  { name: 'Timeline', Icon: Timeline, category: 'data', keywords: ['timeline', 'history', 'events', 'tracking'] },
  { name: 'FactCheck', Icon: FactCheck, category: 'data', keywords: ['fact', 'verify', 'validation', 'quality'] },
  { name: 'PivotTableChart', Icon: PivotTableChart, category: 'data', keywords: ['pivot', 'table', 'report', 'analysis'] },
  { name: 'ViewColumn', Icon: ViewColumn, category: 'data', keywords: ['columns', 'table', 'layout', 'grid'] },

  // Network
  { name: 'Hub', Icon: Hub, category: 'network', keywords: ['hub', 'network', 'connect', 'orchestration'] },
  { name: 'Dns', Icon: Dns, category: 'network', keywords: ['dns', 'domain', 'network', 'routing'] },
  { name: 'Router', Icon: Router, category: 'network', keywords: ['router', 'network', 'wifi', 'connectivity'] },
  { name: 'NetworkCheck', Icon: NetworkCheck, category: 'network', keywords: ['network', 'latency', 'monitoring', 'uptime'] },
  { name: 'Speed', Icon: Speed, category: 'network', keywords: ['speed', 'performance', 'fast', 'optimization'] },
  { name: 'Language', Icon: Language, category: 'network', keywords: ['web', 'global', 'website', 'internet'] },
  { name: 'Wifi', Icon: Wifi, category: 'network', keywords: ['wifi', 'wireless', 'network', 'connectivity'] },
  { name: 'WifiOff', Icon: WifiOff, category: 'network', keywords: ['wifi', 'offline', 'disconnect', 'network'] },
  { name: 'Lan', Icon: Lan, category: 'network', keywords: ['lan', 'network', 'local', 'ethernet'] },
  { name: 'Cable', Icon: Cable, category: 'network', keywords: ['cable', 'wired', 'network', 'connect'] },
  { name: 'Cast', Icon: Cast, category: 'network', keywords: ['cast', 'stream', 'wireless', 'display'] },
  { name: 'CastConnected', Icon: CastConnected, category: 'network', keywords: ['cast', 'connected', 'stream', 'device'] },
  { name: 'SignalCellularAlt', Icon: SignalCellularAlt, category: 'network', keywords: ['cellular', 'mobile', 'signal', 'network'] },
  { name: 'SignalWifi4Bar', Icon: SignalWifi4Bar, category: 'network', keywords: ['wifi', 'signal', 'strength', 'network'] },
  { name: 'ConnectWithoutContact', Icon: ConnectWithoutContact, category: 'network', keywords: ['connect', 'wireless', 'pair', 'network'] },
  { name: 'ShareLocation', Icon: ShareLocation, category: 'network', keywords: ['location', 'geo', 'network', 'map'] },
  { name: 'SwapHoriz', Icon: SwapHoriz, category: 'network', keywords: ['swap', 'transfer', 'exchange', 'sync'] },
  { name: 'CompareArrows', Icon: CompareArrows, category: 'network', keywords: ['compare', 'sync', 'transfer', 'exchange'] },
  { name: 'OfflineBolt', Icon: OfflineBolt, category: 'network', keywords: ['offline', 'power', 'disconnect', 'network'] },
  { name: 'ElectricBolt', Icon: ElectricBolt, category: 'network', keywords: ['power', 'energy', 'fast', 'automation'] },

  // Devices
  { name: 'Devices', Icon: Devices, category: 'devices', keywords: ['devices', 'multi-device', 'responsive', 'platform'] },
  { name: 'Computer', Icon: Computer, category: 'devices', keywords: ['computer', 'desktop', 'workstation', 'it'] },
  { name: 'Smartphone', Icon: Smartphone, category: 'devices', keywords: ['mobile', 'phone', 'app', 'ios', 'android'] },
  { name: 'Tablet', Icon: Tablet, category: 'devices', keywords: ['tablet', 'mobile', 'device', 'touch'] },
  { name: 'Memory', Icon: Memory, category: 'devices', keywords: ['memory', 'ram', 'compute', 'server'] },
  { name: 'Laptop', Icon: Laptop, category: 'devices', keywords: ['laptop', 'notebook', 'portable', 'computer'] },
  { name: 'DesktopWindows', Icon: DesktopWindows, category: 'devices', keywords: ['desktop', 'windows', 'pc', 'workstation'] },
  { name: 'DesktopMac', Icon: DesktopMac, category: 'devices', keywords: ['desktop', 'mac', 'apple', 'workstation'] },
  { name: 'PhoneIphone', Icon: PhoneIphone, category: 'devices', keywords: ['iphone', 'ios', 'mobile', 'apple'] },
  { name: 'PhoneAndroid', Icon: PhoneAndroid, category: 'devices', keywords: ['android', 'mobile', 'phone', 'google'] },
  { name: 'Watch', Icon: Watch, category: 'devices', keywords: ['watch', 'wearable', 'smartwatch', 'device'] },
  { name: 'Tv', Icon: Tv, category: 'devices', keywords: ['tv', 'display', 'screen', 'media'] },
  { name: 'Print', Icon: Print, category: 'devices', keywords: ['print', 'printer', 'document', 'output'] },
  { name: 'Scanner', Icon: Scanner, category: 'devices', keywords: ['scanner', 'scan', 'document', 'input'] },
  { name: 'Keyboard', Icon: Keyboard, category: 'devices', keywords: ['keyboard', 'input', 'typing', 'hardware'] },
  { name: 'Mouse', Icon: Mouse, category: 'devices', keywords: ['mouse', 'input', 'pointer', 'hardware'] },
  { name: 'Headphones', Icon: Headphones, category: 'devices', keywords: ['headphones', 'audio', 'headset', 'sound'] },
  { name: 'Speaker', Icon: Speaker, category: 'devices', keywords: ['speaker', 'audio', 'sound', 'output'] },
  { name: 'CameraAlt', Icon: CameraAlt, category: 'devices', keywords: ['camera', 'photo', 'video', 'capture'] },
  { name: 'Videocam', Icon: Videocam, category: 'devices', keywords: ['video', 'camera', 'conference', 'stream'] },
  { name: 'Monitor', Icon: Monitor, category: 'devices', keywords: ['monitor', 'display', 'screen', 'desktop'] },
  { name: 'DeviceHub', Icon: DeviceHub, category: 'devices', keywords: ['hub', 'device', 'connect', 'peripheral'] },
  { name: 'Usb', Icon: Usb, category: 'devices', keywords: ['usb', 'port', 'connect', 'hardware'] },
  { name: 'SimCard', Icon: SimCard, category: 'devices', keywords: ['sim', 'mobile', 'cellular', 'connectivity'] },
  { name: 'BatteryFull', Icon: BatteryFull, category: 'devices', keywords: ['battery', 'power', 'charge', 'mobile'] },
  { name: 'BatteryChargingFull', Icon: BatteryChargingFull, category: 'devices', keywords: ['charging', 'battery', 'power', 'mobile'] },
  { name: 'MonitorHeart', Icon: MonitorHeart, category: 'devices', keywords: ['monitor', 'health', 'observability', 'status'] },

  // Business
  { name: 'BusinessCenter', Icon: BusinessCenter, category: 'business', keywords: ['business', 'enterprise', 'corporate', 'b2b'] },
  { name: 'WorkOutline', Icon: WorkOutline, category: 'business', keywords: ['work', 'professional', 'service', 'job'] },
  { name: 'Dashboard', Icon: Dashboard, category: 'business', keywords: ['dashboard', 'overview', 'metrics', 'home'] },
  { name: 'Business', Icon: Business, category: 'business', keywords: ['business', 'company', 'office', 'enterprise'] },
  { name: 'AccountBalance', Icon: AccountBalance, category: 'business', keywords: ['bank', 'finance', 'account', 'institution'] },
  { name: 'AccountBalanceWallet', Icon: AccountBalanceWallet, category: 'business', keywords: ['wallet', 'finance', 'payment', 'account'] },
  { name: 'Payment', Icon: Payment, category: 'business', keywords: ['payment', 'billing', 'checkout', 'transaction'] },
  { name: 'CreditCard', Icon: CreditCard, category: 'business', keywords: ['credit', 'card', 'payment', 'billing'] },
  { name: 'Receipt', Icon: Receipt, category: 'business', keywords: ['receipt', 'invoice', 'billing', 'order'] },
  { name: 'AttachMoney', Icon: AttachMoney, category: 'business', keywords: ['money', 'finance', 'cost', 'pricing'] },
  { name: 'MonetizationOn', Icon: MonetizationOn, category: 'business', keywords: ['monetization', 'revenue', 'money', 'pricing'] },
  { name: 'ShoppingCart', Icon: ShoppingCart, category: 'business', keywords: ['cart', 'shop', 'ecommerce', 'purchase'] },
  { name: 'Store', Icon: Store, category: 'business', keywords: ['store', 'shop', 'retail', 'marketplace'] },
  { name: 'Inventory', Icon: Inventory, category: 'business', keywords: ['inventory', 'stock', 'warehouse', 'assets'] },
  { name: 'LocalShipping', Icon: LocalShipping, category: 'business', keywords: ['shipping', 'delivery', 'logistics', 'fulfillment'] },
  { name: 'Work', Icon: Work, category: 'business', keywords: ['work', 'job', 'employment', 'professional'] },
  { name: 'Groups', Icon: Groups, category: 'business', keywords: ['groups', 'team', 'people', 'organization'] },
  { name: 'CorporateFare', Icon: CorporateFare, category: 'business', keywords: ['corporate', 'enterprise', 'company', 'organization'] },
  { name: 'RocketLaunch', Icon: RocketLaunch, category: 'business', keywords: ['launch', 'startup', 'deploy', 'growth'] },
  { name: 'CalendarToday', Icon: CalendarToday, category: 'business', keywords: ['calendar', 'schedule', 'date', 'planning'] },
  { name: 'Schedule', Icon: Schedule, category: 'business', keywords: ['schedule', 'time', 'planning', 'calendar'] },
  { name: 'Task', Icon: Task, category: 'business', keywords: ['task', 'todo', 'work', 'project'] },
  { name: 'Checklist', Icon: Checklist, category: 'business', keywords: ['checklist', 'tasks', 'audit', 'review'] },
  { name: 'Assignment', Icon: Assignment, category: 'business', keywords: ['assignment', 'document', 'task', 'project'] },
  { name: 'Paid', Icon: Paid, category: 'business', keywords: ['paid', 'payment', 'invoice', 'billing'] },
  { name: 'PriceCheck', Icon: PriceCheck, category: 'business', keywords: ['price', 'cost', 'quote', 'billing'] },

  // Communication
  { name: 'Email', Icon: Email, category: 'communication', keywords: ['email', 'mail', 'communication', 'notify'] },
  { name: 'HeadsetMic', Icon: HeadsetMic, category: 'communication', keywords: ['support', 'call', 'helpdesk', 'contact'] },
  { name: 'SupportAgent', Icon: SupportAgent, category: 'communication', keywords: ['support', 'helpdesk', 'service', 'customer'] },
  { name: 'Notifications', Icon: Notifications, category: 'communication', keywords: ['notifications', 'alerts', 'updates', 'push'] },
  { name: 'Search', Icon: Search, category: 'communication', keywords: ['search', 'discover', 'find', 'seo'] },
  { name: 'Chat', Icon: Chat, category: 'communication', keywords: ['chat', 'message', 'conversation', 'support'] },
  { name: 'Forum', Icon: Forum, category: 'communication', keywords: ['forum', 'community', 'discussion', 'chat'] },
  { name: 'Message', Icon: Message, category: 'communication', keywords: ['message', 'sms', 'chat', 'notify'] },
  { name: 'Sms', Icon: Sms, category: 'communication', keywords: ['sms', 'text', 'message', 'mobile'] },
  { name: 'Phone', Icon: Phone, category: 'communication', keywords: ['phone', 'call', 'voice', 'contact'] },
  { name: 'Call', Icon: Call, category: 'communication', keywords: ['call', 'phone', 'voice', 'support'] },
  { name: 'ContactMail', Icon: ContactMail, category: 'communication', keywords: ['contact', 'mail', 'email', 'reach'] },
  { name: 'Send', Icon: Send, category: 'communication', keywords: ['send', 'message', 'deliver', 'notify'] },
  { name: 'Campaign', Icon: Campaign, category: 'communication', keywords: ['campaign', 'marketing', 'email', 'broadcast'] },
  { name: 'MarkEmailRead', Icon: MarkEmailRead, category: 'communication', keywords: ['email', 'read', 'inbox', 'message'] },
  { name: 'NotificationsActive', Icon: NotificationsActive, category: 'communication', keywords: ['notifications', 'alerts', 'active', 'updates'] },
  { name: 'Announcement', Icon: Announcement, category: 'communication', keywords: ['announcement', 'news', 'broadcast', 'alert'] },
  { name: 'RecordVoiceOver', Icon: RecordVoiceOver, category: 'communication', keywords: ['voice', 'audio', 'narration', 'accessibility'] },
  { name: 'Share', Icon: Share, category: 'communication', keywords: ['share', 'social', 'link', 'collaborate'] },
  { name: 'Link', Icon: Link, category: 'communication', keywords: ['link', 'url', 'connect', 'reference'] },
  { name: 'RssFeed', Icon: RssFeed, category: 'communication', keywords: ['rss', 'feed', 'subscribe', 'updates'] },

  // AI
  { name: 'Psychology', Icon: Psychology, category: 'ai', keywords: ['ai', 'ml', 'intelligence', 'smart'] },
  { name: 'SmartToy', Icon: SmartToy, category: 'ai', keywords: ['bot', 'automation', 'ai', 'assistant'] },
  { name: 'AutoAwesome', Icon: AutoAwesome, category: 'ai', keywords: ['ai', 'magic', 'automation', 'enhance'] },
  { name: 'AutoFixHigh', Icon: AutoFixHigh, category: 'ai', keywords: ['auto', 'fix', 'enhance', 'ai'] },
  { name: 'AutoGraph', Icon: AutoGraph, category: 'ai', keywords: ['auto', 'graph', 'analytics', 'ai'] },
  { name: 'Science', Icon: Science, category: 'ai', keywords: ['science', 'research', 'lab', 'experiment'] },
  { name: 'ModelTraining', Icon: ModelTraining, category: 'ai', keywords: ['model', 'training', 'ml', 'ai'] },
  { name: 'TipsAndUpdates', Icon: TipsAndUpdates, category: 'ai', keywords: ['tips', 'suggestions', 'ai', 'insights'] },
  { name: 'Lightbulb', Icon: Lightbulb, category: 'ai', keywords: ['idea', 'innovation', 'insight', 'smart'] },
  { name: 'EmojiObjects', Icon: EmojiObjects, category: 'ai', keywords: ['idea', 'lightbulb', 'innovation', 'creative'] },
  { name: 'Biotech', Icon: Biotech, category: 'ai', keywords: ['biotech', 'science', 'research', 'data'] }
]

export type ItServiceIconName = (typeof IT_SERVICE_ICONS)[number]['name']

const ICON_MAP = new Map<string, IconComponent>(IT_SERVICE_ICONS.map(entry => [entry.name, entry.Icon]))

export function getItServiceIcon(name: string | null | undefined): IconComponent | null {
  if (!name) {
    return null
  }

  return ICON_MAP.get(name) ?? null
}
